name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run the release
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
      - run: nix develop --command bash -c "cd scala && sbt blog/mdoc"

      - env:
          GIT_USER: valdemargr
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name ValdemarGr
          git config --global user.email randomvald0069@gmail.com
          cd site && yarn install && yarn deploy
