name: CI

on:
  push:
    branches: ['**', '!update/**', '!pr/**']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


concurrency:
  group: ${{ github.workflow }} @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build the docs using nix
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v20
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix flake check
      - run: cd scala && sbt docs

      - env:
          GIT_USER: valdemargr
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name ValdemarGr
          git config --global user.email randomvald0069@gmail.com
          cd site && yarn install && yarn deploy
