name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run the release
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
      - run: nix develop --command bash -c "cd scala && sbt blog/mdoc"
      - run: nix develop --command bash -c "cd site && yarn install && yarn build"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./site/build
